### ISSUE TITLE
small bug 

### ISSUE THREAD

**Issue by flier56** [btiteam/xbtit-3.x#1]
small bug

admin.get_support_info.php
 this works

if (get_remote_file('http://www.btiteam.eu')) {
    $btit_url_rss = 'http://www.btiteam.eu/index.php?type=rss;action=.xml;board=83;sa=news';
    $btit_url_last = 'http://www.btiteam.eu/last_version.txt';

 ![control panel](https://user-images.githubusercontent.com/9010706/82126917-e06a7200-977d-11ea-9422-91e29641950d.PNG)	

if i change http to https	i get can not connect to btiteam site in xbtit admin control panel 

https://www.btiteam.eu/index.php?type=rss;action=.xml;board=83;sa=news

in firefox and edge i get this warning
Your connection isn't private
NET::ERR_CERT_COMMON_NAME_INVALID

**Comment by KingCobra58** [comment]
Fixed the typo
