### ISSUE TITLE
Seeding issue

### ISSUE THREAD

**Issue by alwisiax** [btiteam/xbtit-3.x#4]
### Issue Type
- [x] Bug Report
- [ ] Feature Idea
- [ ] Enhancement
- [x] Technical Discussion
- [x] Question

torrent file can be downloaded from server but client (Downloader) cant leech from another client (Seeder) ! also bittorrent seeder give the torrent color red (seed issue).

Announce URL:  http://xxxxxxxxxx.com/announce.php

![Capture](https://user-images.githubusercontent.com/73487018/99313474-4d171400-2868-11eb-81b3-938b178ce3eb.PNG)
![Capture2](https://user-images.githubusercontent.com/73487018/99313777-cf9fd380-2868-11eb-9558-3c2bf8b7eb96.PNG)

**Comment by l3oncoder** [comment]
Normally it best not to start seeding before you upload it to site then once you redown it will have your pid attached to the tracker allowing it to seed, This is an common mistake and isn't an bug with the script

**Comment by alwisiax** [comment]
Thank you it's ok now.
