### ISSUE TITLE
Need some precision about requirements

### ISSUE THREAD

**Issue by jpoggi** [btiteam/xbtit-3.x#5]
### Issue Type
- [ ] Bug Report
- [ ] Feature Idea
- [ ] Enhancement
- [ ] Technical Discussion
- [X] Question

### End User Info
-- XBTIT Version: 3.0.00

-- PHP Version: 7.2.34

-- Database Driver & Version: MySQL 5.7.32

```
mysql> SELECT SCHEMA_NAME 'database', default_character_set_name 'charset', DEFAULT_COLLATION_NAME 'collation' FROM information_schema.SCHEMATA;
+--------------------+---------+-----------------+
| database           | charset | collation       |
+--------------------+---------+-----------------+
| information_schema | utf8    | utf8_general_ci |
| my_database_name   | utf8    | utf8_unicode_ci |
+--------------------+---------+-----------------+
```

-- Web Server Driver & Version: Apache 2.4.38

-- OS Driver and Version: Debian GNU/Linux 10 (buster)

Hi,

First of all thank you for releasing a brand new version of xbtit version !

I have built a Docker php container, link to a mysql container, everything is ok, I can access the install.php.

But I'm a little bit confused on the prerequisites, on the github page it is mentionned:

- PHP 7.2
- MySQL 5.6 or 5.7

And when I acces the install.php, I can see different informations:

- xbtit 3.0.00 (r) requires PHP 5.7 and MySQL 7.1 or better.

Can you enlight me about the correct and latest version supported for this tracker to work ?

The true problem here, is that the install process never ends.

On STEP 3/5 SQL Imp. I'm stuck with a blank page:

![Capture d’écran du 2020-11-20 10-56-05](https://user-images.githubusercontent.com/48477405/99786747-28989180-2b1f-11eb-85a6-48c9017fc2dd.png)

My guess is that there is something missing, a library or anything else ?

Regards.

**Comment by alwisiax** [comment]
> ### Issue Type
> * [ ]  Bug Report
> * [ ]  Feature Idea
> * [ ]  Enhancement
> * [ ]  Technical Discussion
> * [x]  Question
> 
> ### End User Info
> -- XBTIT Version: 3.0.00
> 
> -- PHP Version: 7.2.34
> 
> -- Database Driver & Version: MySQL 5.7.32
> 
> ```
> mysql> SELECT SCHEMA_NAME 'database', default_character_set_name 'charset', DEFAULT_COLLATION_NAME 'collation' FROM information_schema.SCHEMATA;
> +--------------------+---------+-----------------+
> | database           | charset | collation       |
> +--------------------+---------+-----------------+
> | information_schema | utf8    | utf8_general_ci |
> | my_database_name   | utf8    | utf8_unicode_ci |
> +--------------------+---------+-----------------+
> ```
> 
> -- Web Server Driver & Version: Apache 2.4.38
> 
> -- OS Driver and Version: Debian GNU/Linux 10 (buster)
> 
> Hi,
> 
> First of all thank you for releasing a brand new version of xbtit version !
> 
> I have built a Docker php container, link to a mysql container, everything is ok, I can access the install.php.
> 
> But I'm a little bit confused on the prerequisites, on the github page it is mentionned:
> 
> * PHP 7.2
> * MySQL 5.6 or 5.7
> 
> And when I acces the install.php, I can see different informations:
> 
> * xbtit 3.0.00 (r) requires PHP 5.7 and MySQL 7.1 or better.
> 
> Can you enlight me about the correct and latest version supported for this tracker to work ?
> 
> The true problem here, is that the install process never ends.
> 
> On STEP 3/5 SQL Imp. I'm stuck with a blank page:
> 
> ![Capture d’écran du 2020-11-20 10-56-05](https://user-images.githubusercontent.com/48477405/99786747-28989180-2b1f-11eb-85a6-48c9017fc2dd.png)
> 
> My guess is that there is something missing, a library or anything else ?
> 
> Regards.

I think it is MYSQL db. user credential problem! try to reassign the password of db user. remember to grant him all to *.*

**Comment by jpoggi** [comment]
Hi @alwisiax ,

A friend help me, and I was using the wrong MySQL driver.

pdo_mysql instead of mysqli.

Regards
